# Generated by Django 3.1 on 2021-03-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0003_auto_20210302_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='role',
            field=models.CharField(choices=[('participant', 'participant'), ('instructor', 'instructor')], db_index=True, default='', max_length=20),
        ),
    ]
