# Generated by Django 3.1 on 2021-03-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0004_userseminar_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='now_capacity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
