# Generated by Django 3.1 on 2021-03-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0005_seminar_now_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
