# Generated by Django 3.1 on 2021-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0006_userseminar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseminar',
            name='dropped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
