# Generated by Django 3.1 on 2021-03-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0007_userseminar_dropped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminar',
            name='now_capacity',
        ),
    ]
