# Generated by Django 3.1 on 2021-03-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210218_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantprofile',
            name='accepted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
