# Generated by Django 3.1 on 2021-03-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210311_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
